[package]
name = "vulkaning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ash = { version = "0.37.3", features = ["linked"] }
bytemuck = { version = "1.14.0", features = ["derive"] }
env_logger = "0.10.1"
glam = { version = "0.24.2", features = ["bytemuck"] }
image = "0.24.7"
log = "0.4.20"
raw-window-handle = "0.6.0"
winit = "0.29.3"
