[package]
name = "vulkaning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
ash = { version = "0.37.3", features = ["linked"] }
ash-window = "0.12.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
color-eyre = "0.6.2"
env_logger = "0.10.1"
glam = { version = "0.24.2", features = ["bytemuck"] }
gpu-alloc = "0.6.0"
gpu-alloc-ash = "0.6.0"
image = "0.24.7"
log = "0.4.20"
num = "0.4.1"
raw-window-handle = "0.5"

[dependencies.winit]
version = "0.29"
features = ["rwh_05"]

[build-dependencies]
anyhow = "1.0"
shaderc = "0.8"
