[env]
RUST_LOG = "debug"
RUST_BACKTRACE = "full"
SHADER_BUILD_DIR = "shaderbuild"

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
