[env]
RUST_LOG = "info"
RUST_BACKTRACE = "1"
SHADER_BUILD_DIR = "./shaderbuild"
ASSETS_DIR = "./assets"

[tasks.debug]
env = { RUST_LOG = "debug" }
command = "cargo"
args = ["run"]

[tasks.trace]
env = { RUST_LOG = "trace" }
command = "cargo"
args = ["run"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
